### ISSUE TITLE
Incorrect string value error

### ISSUE THREAD

**Issue by gmarcus** [josephsu/EPFImporter#1]
Thanks for the great mods.  I was hopeful it would go smoothly but I am seeing the following error when importing:

```
2013-02-20 17:46:42,940 [ERROR]: Fatal error encountered while ingesting '/Users/glenn/Desktop/epf/itunes20130213/application'
Traceback (most recent call last):
  File "/Users/glenn/Development/EPFImporter/EPFIngester.py", line 129, in ingestFull
    self._populateTable(self.tmpTableName, skipKeyViolators=skipKeyViolators)
  File "/Users/glenn/Development/EPFImporter/EPFIngester.py", line 379, in _populateTable
    cur.execute(exStr)
  File "build/bdist.macosx-10.8-intel/egg/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "build/bdist.macosx-10.8-intel/egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x8C\\x9F\\xF0\\x9F...' for column 'description' at row 112")
```

I have my database set to use UTF8.

Any thoughts?

Best,
Glenn

**Comment by jpmurray** [comment]
It's worth to add, if anyone else stumble upon this, that you _have to_ change your default database encoding also: `mysql> ALTER DATABASE DEFAULT CHARSET 'utf8mb4';`.

It's the only thing in this repo's version of `installation.rtf` that changes, and I missed it at first, and it can cause encoding problems too.

**Comment by miachenberkeley** [comment]
Hello, I setup the charset to "utf8mb4" and still have an encoding problem
```
Traceback (most recent call last):
  File "/Users/miachen/Desktop/EPFimporter/EPF_Importer/EPFIngester.py", line 129, in ingestFull
    self._populateTable(self.tmpTableName, skipKeyViolators=skipKeyViolators)
  File "/Users/miachen/Desktop/EPFimporter/EPF_Importer/EPFIngester.py", line 379, in _populateTable
    cur.execute(exStr)
  File "/Library/Python/2.7/site-packages/MySQL_python-1.2.4b4-py2.7-macosx-10.12-intel.egg/MySQLdb/cursors.py", line 202, in execute
    self.errorhandler(self, exc, value)
  File "/Library/Python/2.7/site-packages/MySQL_python-1.2.4b4-py2.7-macosx-10.12-intel.egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x8C\\x9F\\xF0\\x9F...' for column 'description' at row 29")
2017-08-02 15:10:23,240 [ERROR]: Last record ingested before failure: 5400
2017-08-02 15:10:23,241 [INFO]: Import of itunes20170222 completed at: 17-08-02 15:10:23
2017-08-02 15:10:23,241 [INFO]: Total import time for itunes20170222: 0:00:01.02
2017-08-02 15:10:23,241 [WARNING]: The following files encountered errors and were not imported:
 application
2017-08-02 15:10:23,242 [WARNING]: The following files encountered errors and were not imported:
        itunes20170222/['application']
2017-08-02 15:10:23,242 [INFO]: Total import time for all directories: 0:00:01.02
```

**Comment by josephsu** [comment]
@miachenberkeley can you test 
 the latest commit https://github.com/josephsu/EPFImporter/commit/4726d061108c936e0082971d91c68b4c436d266e ?

Also note that some EPF record contains separator character \u0001 within field values and thus confuse parser.

**Comment by Behinder** [comment]
Same problem here. changing charset not solved problem.

**Comment by josephsu** [comment]
What's the error message?

**Comment by Behinder** [comment]
![zrzut ekranu 2017-12-27 o 11 56 27](https://user-images.githubusercontent.com/591766/34396431-12fcbe4c-eb6b-11e7-9df0-2fa7babbaf61.png)
![zrzut ekranu 2017-12-27 o 11 55 35](https://user-images.githubusercontent.com/591766/34396435-207dd72c-eb6b-11e7-9976-72e4547be552.png)

**Comment by infinitedreams9586** [comment]
I am having the same issue. Any one was able to resolve it..??

**Comment by Behinder** [comment]
Probably you need to throw this line out using awk before insert to database
